title:  Thiago Henrique F. Correa # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Frontend Developer
  <br><br>
  CS student  
  <br><br>
  <a href="https://www.linkedin.com/in/thiago-henrique-ferreira-correa-706b0389/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
